package se.kth.peiyan.cimCracker;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * the initial panel displayed at the middle of main frame
 * 
 * @author peiyanli
 * @version 0.1, May 16, 2015
 */
public class PnlInitial extends javax.swing.JPanel {

    /**
     * Creates new form initalPanel
     */
    public PnlInitial() {
        initComponents();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension dimension = toolkit.getScreenSize();
        setPreferredSize(new Dimension(dimension.height * 2 / 3, dimension.height / 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.JLabel lblInitalText = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblInitalText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInitalText.setText("<html><h2><center><font color=\"#505050\">Open One CIM File or Database to Start</font></center><h2></html>");
        add(lblInitalText, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
